///////////////////////////////////////////////////////////
//  CCharacterData.as
//  Macromedia ActionScript Implementation of the Class CCharacterData
//  Generated by Enterprise Architect
//  Created on:      15-����-2012 10:17:54
//  Original author: Administrator
///////////////////////////////////////////////////////////

package utils
{
	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 15-����-2012 10:17:54
	 */

	public class CCharacterData
	{
		public var camp: uint = 0;
		public var uid: String = '';
		public var uname: String;
		public var level: uint;
		private var missionList: Array;
		private static var instance: CCharacterData;
		private static var allowInstance: Boolean = false;

		public function CCharacterData()
		{
		}
		
		public function getPlayerData(): void
		{
			
		}

		public function get AllMissionList(): Array
		{
			return missionList;
		}

		public function get CanSeeMissionList(): Array
		{
			return missionList;
		}

		public function initMissionList(): void
		{
		}

	} //end CCharacterData

}